[project]
name = "affordmed"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi[all,standard]>=0.116.0",
    "loguru>=0.7.3",
    "requests>=2.32.4",
    "ruff>=0.12.2",
]
